use_frameworks!

platform :ios, '8.0'

target 'CalculateWaypoint_Example' do
  pod 'CalculateWaypoint', :path => '../'

  target 'CalculateWaypoint_Tests' do
    inherit! :search_paths

    
  end
end
